import { company } from "@/config/company";
import { materials, shapes } from "@/config/catalog";
import { defaultInput } from "@/lib/configuration/input";
import { generateModel } from "@/lib/geometry/generate";
import { ModelDiagram } from "@/components/viewer/ModelDiagram";
import Calculator from "@/components/calculator/Calculator";
import ChooseShape from "@/components/landing/ChooseShape";
import LeadForm from "@/components/landing/LeadForm";

const services = [
  ["01", "Проектирование", "Компоновка, рабочая документация КМ и КМД, узлы и спецификации для изготовления."],
  ["02", "Изготовление", "Стойки, рамы, фермы и трубчатые элементы по согласованной рабочей документации."],
  ["03", "Комплектация", "Подбор заполнения, креплений и покрытия. Состав поставки фиксируется в предложении."],
  ["04", "Монтаж", "Сборка конструкций и заполнения на объекте. Условия и регион работ согласуются отдельно."],
];
const faqs = [
  ["Можно обратиться без готового проекта?", "Да. Начните с размеров объекта, региона и задачи. Инженер уточнит исходные данные и предложит состав проектных работ."],
  ["Вы работаете по нашим чертежам?", "Проект можно передать на проверку и оценку изготовления. Напишите об этом в заявке или свяжитесь с отделом изготовления по контактам ниже."],
  ["3D-калькулятор выполняет расчёт прочности?", "Он создаёт предварительную компоновку и считает геометрические объёмы. Сечения, соединения, основания, ветровые и снеговые нагрузки определяются в проекте. Эффективность защиты не устанавливается по 3D-схеме."],
  ["Почему калькулятор не показывает цену в рублях?", "Стоимость зависит от профилей, заполнения, покрытий, условий доставки и монтажа. Тарифы должны быть подтверждены компанией. Сейчас схема передаётся инженеру для индивидуального предложения."],
  ["Чем отличается сетчатое заполнение от трубчатого?", "Это разные материалы и схемы крепления. В конфигураторе можно сравнить внешний вид и геометрические объёмы. Окончательный материал и его характеристики выбираются при проектировании."],
  ["Можно заказать только проектирование или изготовление?", "Да. Выберите нужные работы в конфигураторе или укажите их в заявке. Состав и границы работ согласуются в договоре."],
  ["В каких регионах выполняется монтаж?", "Укажите регион объекта в заявке. Возможность доставки, выезда и монтажа подтвердит компания с учётом объёма и условий работ."],
  ["Какие документы получу?", "Состав документации фиксируется в договоре: КМ, КМД, спецификации и монтажные схемы — в зависимости от заказанных работ. Документы на материалы и изделия согласуются при комплектации."],
];
export default function LandingPage({ calculatorVariant = "standard" }: { calculatorVariant?: "standard" | "wide" | "compact" }) {
  const wide = calculatorVariant !== "standard";
  const hero = generateModel({ ...structuredClone(defaultInput), shapeId: "C3", length: 12, width: 7, height: 4, roofMaterialId: "M6", structuralSystem: "spatial-truss" });
  return <>
    <a className="skip-link" href="#main-content">Перейти к содержанию</a>
    <header className="site-header"><div className="container header-inner">
      <a className="brand" href="/" aria-label={company.shortName + " — на главную"}><span className="brand-mark" aria-hidden="true">Т</span><span>{company.shortName}<small>Инженерные конструкции</small></span></a>
      <nav aria-label="Основная навигация"><a href="#solutions">Решения</a><a href="#calculator">3D-конфигуратор</a><a href="#services">Услуги</a><a href="#contacts">Контакты</a></nav>
      <a className="header-phone" href={company.contacts.general.phone.href}>{company.contacts.general.phone.display}<small>Обсудить проект</small></a>
    </div></header>
    <main id="main-content">
      <section className="hero container"><div className="hero-copy"><p className="eyebrow">Проектирование · Изготовление · Монтаж</p><h1>Металлоконструкции<br />для антидроновой<br /><span>защиты</span></h1><p className="hero-description">Каркасы, защитные экраны и укрытия под размеры вашего объекта. От предварительной схемы до рабочей документации и монтажа.</p><div className="hero-actions"><a className="button button-primary" href="#calculator">Собрать 3D-схему <span aria-hidden="true">↗</span></a><a className="button button-outline" href="#contacts">У меня есть проект</a></div><div className="hero-features"><span>КМ и КМД</span><span>Разные типы заполнения</span><span>По габаритам объекта</span></div></div><div className="hero-visual"><div className="drawing-head"><span>Предварительная компоновка</span><span>01 / НАВЕС</span></div><ModelDiagram graph={hero} /><div className="drawing-dimensions"><span>12 000 × 7 000 × 4 000 мм</span><span>Трубчатое покрытие</span></div><p>Показана условная схема. Профили и узлы подбираются при проектировании.</p></div></section>
      <section className="section section-tint" id="solutions"><div className="container"><div className="section-heading"><div><p className="eyebrow">Конструктивные решения</p><h2>Подберите форму<br />для вашего объекта</h2></div><p>От отдельного экрана до нескольких защитных контуров. Начните с формы — размеры и заполнение можно изменить в конфигураторе.</p></div><div className="solution-grid">{shapes.map((shape, i) => {
        const graph = generateModel({ ...structuredClone(defaultInput), shapeId: shape.id, length: 5, width: 3, height: 2.8, diameter: 4, rise: 1, materialId: "M4", roofMaterialId: "M6", variant: shape.id === "C5" ? "shelter" : shape.id === "C6" ? "arch" : shape.id === "C7" ? "dome" : "portal", contours: [{ enabled: true, offset: 0.5, height: 3.3 }, { enabled: true, offset: 1.2, height: 4 }, { enabled: false, offset: 2, height: 5 }] });
        return <article className="solution-card" key={shape.id}><div className="solution-image"><span className="card-index">0{i + 1}</span><ModelDiagram graph={graph} /></div><h3>{shape.name}</h3><p>{shape.description}</p><ChooseShape shapeId={shape.id} /></article>;
      })}</div></div></section>
      <section className="section" id="calculator"><div className="container"><div className="section-heading"><div><p className="eyebrow">Ваш объект — ваша компоновка</p><h2>Посмотрите конструкцию в 3D</h2></div><p>Укажите размеры, выберите материалы и сохраните схему. Геометрия и ведомость обновляются вместе с параметрами.</p></div></div>{calculatorVariant === "wide" ? <Calculator variant="wide" /> : <div className="container"><Calculator variant={calculatorVariant} /></div>}<div className="container layout-comparison" aria-label="Варианты конфигуратора"><a href="/#calculator" aria-current={!wide ? "page" : undefined}>Боковая панель</a><a href="/wide#calculator" aria-current={calculatorVariant === "wide" ? "page" : undefined}>Широкий вид</a><a href="/compact#calculator" aria-current={calculatorVariant === "compact" ? "page" : undefined}>Маленькие карточки</a></div></section>
      <section className="section section-tint" id="materials"><div className="container"><div className="section-heading"><div><p className="eyebrow">Заполнение и комплектующие</p><h2>От сетчатого полотна<br />до стальных труб</h2></div><p>Материал выбирается под проект. Характеристики, крепления и условия замены согласуются по документам производителя.</p></div><div className="material-grid">{materials.map(m => <article key={m.id} className="material-card"><div className={"material-swatch " + m.appearance} aria-hidden="true" /><h3>{m.name}</h3><p>{m.description}</p><small>{m.information.join(" · ")}</small></article>)}</div></div></section>
      <section className="section services-section" id="services"><div className="container"><div className="section-heading"><div><p className="eyebrow">Один проект. Нужный состав работ.</p><h2>От идеи до конструкции<br />на объекте</h2></div><p>Можно заказать отдельный этап или согласовать комплекс работ. Начинаем с исходных данных и понятной спецификации.</p></div><div className="service-grid">{services.map(([n, title, description]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
      <section className="section container production-section"><div><p className="eyebrow">Инженерный подход</p><h2>Сначала проект.<br />Затем металл.</h2><p>Правильная компоновка учитывает доступ к оборудованию, обслуживание и монтаж. Чертежи связывают размеры, элементы и соединения в одну систему.</p><a className="text-link" href={company.websiteUrl}>Подробнее о бюро {company.shortName} <span aria-hidden="true">↗</span></a></div><div className="production-list"><div><span>01</span><h3>Фиксируем исходные данные</h3><p>Габариты, регион, ограничения площадки, проёмы и существующие конструкции.</p></div><div><span>02</span><h3>Согласуем документацию</h3><p>Компоновка, профили, узлы, заполнение и покрытия отражаются в проекте.</p></div><div><span>03</span><h3>Определяем поставку и монтаж</h3><p>Состав изделий и границы работ становятся частью предложения и договора.</p></div></div></section>
      <section className="section section-tint" id="process"><div className="container"><p className="eyebrow">Как мы работаем</p><h2>Четыре шага к реализации</h2><div className="process-grid">{[["Заявка и размеры", "Пришлите задачу или соберите предварительную схему."], ["Уточнение решения", "Инженер проверит исходные данные и состав работ."], ["Предложение и проект", "Согласуем стоимость, документацию и условия выполнения."], ["Изготовление и монтаж", "Работаем по согласованным чертежам и составу поставки."]].map(([t, d], i) => <article key={t}><span>0{i + 1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
      <section className="section container documents-section"><div><p className="eyebrow">Документы по согласованному объёму</p><h2>Понятный состав проекта</h2><p>Перечень выдаваемой документации зависит от вашего заказа и фиксируется до начала работ.</p></div><div className="document-grid">{[["КМ", "Схемы и конструктивные решения"], ["КМД", "Чертежи для изготовления"], ["Ведомости", "Элементы, материалы и комплектующие"], ["Монтаж", "Схемы сборки и узлы соединений"]].map(([a, b]) => <div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></section>
      <section className="section section-tint" id="faq"><div className="container faq-layout"><div><p className="eyebrow">Вопросы до начала работ</p><h2>Что стоит уточнить</h2><p>Если ваш объект требует особого решения, опишите задачу инженеру.</p><a className="text-link" href="#contacts">Связаться с нами ↗</a></div><div className="faq-list">{faqs.map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
      <section className="section container contacts-section" id="contacts"><div className="contact-copy"><p className="eyebrow">Начнём с вашей задачи</p><h2>Обсудим конструкцию<br />и состав работ</h2><a className="contact-phone" href={company.contacts.general.phone.href}>{company.contacts.general.phone.display}</a><a className="contact-email" href={company.contacts.general.email.href}>{company.contacts.general.email.address}</a><div className="contact-departments">{(["design", "manufacturing"] as const).map(key => <div key={key}><strong>{company.contacts[key].label}{key === "manufacturing" ? " и монтаж" : ""}</strong><a href={company.contacts[key].phone.href}>{company.contacts[key].phone.display}</a><a href={company.contacts[key].email.href}>{company.contacts[key].email.address}</a></div>)}</div><address>{company.officeAddress}</address><p className="contact-hours">{company.workingHours.display}<br />Время московское</p><a className="text-link" href={company.sourceUrl}>Контакты на основном сайте ↗</a></div><LeadForm /></section>
    </main>
    <footer className="site-footer"><div className="container"><div className="footer-top"><a className="brand" href="/">{company.shortName}</a><p>Проектирование, изготовление<br />и монтаж металлоконструкций</p><a href={company.websiteUrl}>Основной сайт ↗</a></div><div className="footer-bottom"><p>{company.publishedLegalEntity.name} · ИНН {company.publishedLegalEntity.inn} · ОГРН {company.publishedLegalEntity.ogrn}</p><div><a href="/privacy">Политика обработки данных</a><a href="/consent">Согласие на обработку</a></div></div><p className="footer-note">3D-схемы служат для предварительной компоновки. Окончательное конструктивное решение и условия поставки определяются проектом и договором.</p></div></footer>
    <div className="mobile-actions"><a href={company.contacts.general.phone.href}>Позвонить</a><a href="#calculator">Собрать 3D-схему ↗</a></div>
  </>;
}
